yamlservices:
  - type: web
    name: oilgasfinder-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.17.0
    autoDeploy: true

  - type: static
    name: oilgasfinder-frontend
    staticPublishPath: ./frontend/dist
    buildCommand: cd frontend && npm install && npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
